name: Python CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
    - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-vesion: '3.12.9'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        if [ -f pyproject.toml ]; then pip install .; else pip install pytest==7.1.1; fi
    
    - name: Run tests
      run: |
       pytest tests
